### ISSUE TITLE
Footer improvement

### ISSUE THREAD

**Issue by arya312** [onesoft-sudo/tes-website#8]
The footer of this website could be improved by simply shifting the "The Everything Server" in the lower block and putting the "About" and "Resources" sections above it symmetrically to make it look more interactive and prettier.

**Comment by virtual-designer** [comment]
Thanks for creating the issue! I will keep in this in mind and test it out and see how does it look like after moving the "The Everything Server" section in footer.

**Comment by arya312** [comment]
Hi! Should I take this issue and suggest changes myself through the pull request?

**Comment by killerclaws12** [comment]
Hey! I am the other developer of this project. I believe you can do that. You may suggest features via PR!

**Comment by arya312** [comment]
Great, thanks! Will get back to you with the changes.

**Comment by killerclaws12** [comment]
Alright! 👻 🎃

**Comment by virtual-designer** [comment]
👍🏻
